import pygame
COLUMNS =10
ROWS = 20
CELL_SIZE = 30
GAME_WIDTH,GAME_HEIGHT = COLUMNS*CELL_SIZE,ROWS*CELL_SIZE


#side bar size
SIDEBAR_WIDTH = 200
PREVIEW_HEIGHT_FRACTION = 0.7
SCORE_HEIGHT_FRACTION = 1-PREVIEW_HEIGHT_FRACTION


#window
PADDING = 20
WINDOW_WIDTH = GAME_WIDTH+SIDEBAR_WIDTH+PADDING*3#between the side and the game, and the to borders
WINDOW_HEIGHT = GAME_HEIGHT+PADDING*2


#colours
YELLOW = "#f1e60d"